README.md: Add cEP--0015.md
coala/cEPs pull request #162
Opened 2018-06-01 09:32 UTC by nvzard

Closes https://github.com/coala/cEPs/issues/161

2018-06-01 11:07 UTC, sangamcse requested changes

2018-06-01 11:07 UTC, sangamcse commented on README.md
> +| [cEP-0015](cEP-0015.md) | corobo Enhancement                 | This cEP describes the details of enhancement for corobo in terms of security, tests and configurability as part of the [GSoC'18 Proje
For the consistency, it will be better to make it: `as part of the [GSoC'18 Project]` --> `as a part of the [GSoC'18 project]`

2018-06-02 07:50 UTC, sangamcse commented on README.md
> +| [cEP-0015](cEP-0015.md) | corobo Enhancement                 | This cEP describes the details of enhancement for corobo in terms of security, tests and configurability as a part of the [GSoC'18 pro
Remove 1 space @nvzard

2018-06-02 07:51 UTC, sangamcse commented on README.md
> +| [cEP-0015](cEP-0015.md) | corobo Enhancement                 | This cEP describes the details of enhancement for corobo in terms of security, tests and configurability as a part of the [GSoC'18 pro
Also, make correction of shortlog of the commit message.

2018-06-03 21:10 UTC, jayvdb commented
Invalid PR. the cep doesnt exist yet.

2018-06-03 21:10 UTC, closed without merging