cEP-0035: Extending support for newer versions of Python
coala/cEPs pull request #192
Opened 2021-05-21 16:44 UTC by anshalshukla

This proposal describes the approach that will be followed
to enable coala work with newer version of Python.

closes #191

2021-05-23 15:35 UTC, abhishalya requested changes
This looks very vague in terms of the changes being made as a part of the project. It is important to pinpoint the changes as much as possible. A lot of which is already available in your project.

2021-05-23 15:35 UTC, abhishalya commented on cEP-0035.md
> +| Authors  | Anshal Shukla <mailto:shukla.anshal85@gmail.com> |
Could improve the formatting here a bit.

2021-05-23 15:35 UTC, abhishalya commented on cEP-0035.md
> +This cEP describes the upgrades and steps required to enable coala to support newer versions of Python. This project has been taken up as a [GSoC](https://summerofcode.withgoogle.com/organizations/64
Mention the GSoC year, also this line is too long, please use a decent max line length.

2021-05-23 15:35 UTC, abhishalya commented on cEP-0035.md
> +### 1. Keeping the CI/CD pipeline green
Let's not use numbers in headings.

2021-06-02 16:14 UTC, abhishalya commented
Please no more commits like `aa`, `aaa`. It's an extremely bad practice to write such commits.

2021-06-03 20:55 UTC, anshalshukla commented
I had to change the commit message to "Add support for newer versions of Python" because having "Extending" makes the commit headlog imperative. coala throws an error with that. Let me know if I should change that project-wide.

2021-06-05 04:41 UTC, abhishalya requested changes
This is looking much better than before, just take care of few comments mentioned inline. Also use a spell checker to ensure there are no typos or grammar errors.

2021-06-05 04:41 UTC, abhishalya commented on cEP-0035.md
> +| Authors  | Anshal Shukla <mailto:shukla.anshal85@gmail.com> |
You can improve formatting a bit here.

2021-06-05 04:41 UTC, abhishalya commented on cEP-0035.md
> +This cEP describes the upgrades and steps required to enable coala to support newer versions of Python. This project has been taken up as a [GSoC'21](https://summerofcode.withgoogle.com/organizations
Group all links at the bottom and use them here.

2021-06-05 04:41 UTC, abhishalya commented on cEP-0035.md
> +coala, as of now, supports python up to version 3.6, which is quite old. Lack of support of newer versions of python has been a significant hurdle in the development of coala. Version 3.6 was release
Respect line length please.

2021-06-05 04:41 UTC, abhishalya commented on cEP-0035.md
> +TThe project's primary goal is to enable coala to support newer versions of Python, but this will be attained in multiple smaller steps. The goal is not just to facilitate support for newer versions
coala-bears.

2021-06-05 04:41 UTC, abhishalya commented on cEP-0035.md
> +Currently, the bears CI is broken, so I will start by fixing it.
Not required.

2021-06-05 04:41 UTC, abhishalya commented on cEP-0035.md
> +Throughout the project, it needs to be ensured that the CI/CD pipeline remains unbroken as it is crucial for running the test suite, which is necessary for PR to get merged. This can be ensured by ma
cEP should only focus on the potential enhancements, and it doesn't have to revolve around the project.

2021-06-05 04:41 UTC, abhishalya commented on cEP-0035.md
> +The dependency_management system provides a Python API for familiar package managers. It provides a generic method to install dependencies in the host operating system. It has been a while since it h
Again same point as above, sentences like `will upgrade, will enable` etc do not seem fit for the cEP. This is basically just a plain list of enhancements, not the project proposal.

2021-06-05 04:41 UTC, abhishalya commented on cEP-0035.md
> +Currently bears don't support newer pip versions, changes will be made to fix that. This is essential as while installing the latest version of a Python package might fail or install at a slower rate
Please improve the wordings as mentioned in previous points, not mentioning them again to reduce clutter. Just try to give factual info here.

2021-06-06 04:32 UTC, abhishalya commented
@anshalshukla Please make necessary changes, and rebase. This needs to be merged today.

2021-06-06 04:53 UTC, anshalshukla commented
@abhishalya Will do it soon.

2021-06-06 08:58 UTC, anshalshukla commented
@abhishalya, I guess this looks fine now?

2021-06-06 15:03 UTC, abhishalya commented
Resolve conflicts as well please.

2021-06-06 15:09 UTC, abhishalya requested changes

2021-06-06 15:09 UTC, abhishalya commented on cEP-0035.md
> +
Redundant line.

2021-06-06 15:17 UTC, abhishalya requested changes

2021-06-06 15:17 UTC, abhishalya commented on cEP-0035.md
> +Python up to version 3.6, which is  quite old. Version 3.6 was
```suggestion
Python up to version 3.6, which is quite old. Version 3.6 was
```

2021-06-06 15:17 UTC, abhishalya commented on cEP-0035.md
> +Fix docker image to serve latest version of coala and bears.
```suggestion
Fix docker image to serve the latest version of coala and bears.
```

2021-06-06 17:07 UTC, anshalshukla commented
@abhishalya Done!

2021-06-06 18:07 UTC, abhishalya submitted a review, later dismissed
Nice work :)

2021-06-07 15:40 UTC, abhishalya commented
@anshalshukla You didn't write valid commit short log. Please read the commit guidelines thoroughly.

2021-06-09 03:14 UTC, bkhanale approved these changes

2021-06-11 16:25 UTC, anshalshukla commented
@abhishalya Can I get this merged now.

2021-06-11 16:26 UTC, abhishalya approved these changes

2021-06-11 16:27 UTC, merged