cEP-0005.md: Defines way to name aspects and settings
coala/cEPs pull request #67
Opened 2017-03-19 06:28 UTC by EverWinter23

2017-03-19 13:01 UTC, Techievena commented on cEP-0005.md
> +## Settings
I think its better we have definition of tastes instead of settings. Moreover which issue is this related to? Have a proper commit message.

2017-03-20 14:59 UTC, meetmangukiya commented
Squash the commits

2017-03-20 16:38 UTC, EverWinter23 commented
Done

2017-03-23 17:59 UTC, jack17529 reviewed
No commit message body , please read how to wright good commit messages.

2017-03-23 18:44 UTC, yashtrivedi96 reviewed
Using bulleted list will make it better. Apply bulleted list for Aspects and Settings.
eg This "Then give it settings, e.g. Metadata.CommitMessage.Shortlog.Length can have a setting max_shortlog_length." is not reflected on a new line.

-item1
-item2
will be reflected as 
- item1
- item2

2017-03-23 19:39 UTC, jack17529 commented
@yashtrivedi96  is there any place where we can check these cool things about bulleted list showing and etc as my 1 doc issue is still floating.

2017-03-23 20:08 UTC, yashtrivedi96 commented
http://docutils.sourceforge.net/docs/user/rst/quickref.html

2017-03-23 20:09 UTC, yashtrivedi96 commented
That is for rst

2017-03-23 20:20 UTC, yashtrivedi96 commented
For markdown https://guides.github.com/features/mastering-markdown/

2017-03-23 20:40 UTC, userzimmermann requested changes
settings --> tastes

2017-03-23 20:40 UTC, userzimmermann commented on cEP-0005.md
> +## Settings
@EverWinter23 As @Techievena mentioned it's really important to rename *settings* to *tastes*, since the latter is the new official term.

2017-03-25 10:21 UTC, EverWinter23 commented
will make the changes

2017-03-31 22:30 UTC, userzimmermann requested changes
#69 :)

2017-03-31 22:30 UTC, userzimmermann commented on cEP-0005.md
> +## Aspects
Please keep the terms *aspect* and *aspects* lower case according to #69

2017-04-08 09:55 UTC, userzimmermann commented
@EverWinter23 Still working on this or want someone else to take over? :)

2017-05-29 18:48 UTC, userzimmermann commented
@EverWinter23 Closing this in favor of https://github.com/coala/cEPs/pull/72 , which is based on your PR! Thanks for your work :)

2017-05-29 18:48 UTC, closed without merging