cEP-0010: coala's Command Line Interface
coala/cEPs pull request #79
Opened 2017-05-12 15:35 UTC by Nosferatul

This cEP describe the design of coala's Command Line Interface(the action
selection screen). It is intended to refactor the design.

Closes https://github.com/coala/cEPs/issues/76

2017-05-16 13:12 UTC, Udayan12167 commented
Hey can I request mockups here for the interface? Maybe I'm reviewing too early if you plan to add please ignore.

2017-05-16 13:37 UTC, Nosferatul commented
Sure, I think I'll add them tomorrow

2017-05-18 12:27 UTC, Adrianzatreanu commented on cEP-0010.md
> +This cEP describes the design of coala's Command Line Interface (the action selection screen). It intended to refactor the designed released as part of coala 0.8.
intends

2017-05-18 12:27 UTC, Adrianzatreanu commented on cEP-0010.md
> +This cEP describes the design of coala's Command Line Interface (the action selection screen). It intended to refactor the designed released as part of coala 0.8.
i think its "the design released"

2017-05-18 12:29 UTC, Adrianzatreanu commented on cEP-0010.md
> +Adds functionality alongside with a better interaction with the user. The final goal is coala CLI to be more friendly, easier to read and use, more functionality depending on what user wants!
is for*

2017-05-18 12:30 UTC, Adrianzatreanu commented on cEP-0010.md
> +Adds functionality alongside with a better interaction with the user. The final goal is coala CLI to be more friendly, easier to read and use, more functionality depending on what user wants!
last part after the last comma doesnt even have a verb

2017-05-18 12:38 UTC, Adrianzatreanu commented on cEP-0010.md
> +The below section describes why we should make these changes.
the section below* sounds better

2017-05-19 21:23 UTC, Nosferatul commented
@Udayan12167 please check https://docs.google.com/forms/d/e/1FAIpQLSd-E9cmq6FTJy01kLiiO0WrEcYAgIIpLjwHxTiYzZVjPo5xag/viewform?usp=sf_link

2017-05-21 15:23 UTC, Nosferatul commented
@Adrianzatreanu @yukiisbored please review

2017-05-22 04:23 UTC, yukiisbored commented on cEP-0010.md
> +### Add a 'select action for all results' option
Does all action refers to all of the action inside the section/bear or all of them regardless of which section/bear?

2017-05-22 07:26 UTC, Nosferatul commented on cEP-0010.md
> +### Add a 'select action for all results' option
I was thinking about inside the section/bear

2017-05-22 08:51 UTC, Adrianzatreanu commented on cEP-0010.md
> +This cEP describes the design of coala's Command Line Interface (the action selection screen). It intended to refactor the design released as part of coala 0.8.
intends* ?

2017-05-22 08:52 UTC, Adrianzatreanu commented on cEP-0010.md
> +Adds functionality alongside with a better interaction with the user. The final goal is for coala CLI to be more friendly, easier to read and use. Adds more functionality depending on what user wants
This cEP adds..

2017-05-22 08:52 UTC, Adrianzatreanu commented on cEP-0010.md
> +Adds functionality alongside with a better interaction with the user. The final goal is for coala CLI to be more friendly, easier to read and use. Adds more functionality depending on what user wants
cut the last phrase, sounds cheesy

2017-05-22 08:52 UTC, Adrianzatreanu commented on cEP-0010.md
> +5. Make ApplyPatchAction log the applied patch
enclose ApplyPatchAction in double backticks

2017-05-22 08:53 UTC, Adrianzatreanu commented on cEP-0010.md
> +Most of the people who use a CLI program do not read the whole output, only a small part of it. Also, a large output from a command could tire them and could make them stop using our product We want
such long lines. please restrict the length of a line to 80 chars.

2017-05-22 08:53 UTC, Adrianzatreanu commented on cEP-0010.md
> +Most of the people who use a CLI program do not read the whole output, only a small part of it. Also, a large output from a command could tire them and could make them stop using our product We want
period after "product"

2017-05-22 08:54 UTC, Adrianzatreanu commented on cEP-0010.md
> +Most of the people who use a CLI program do not read the whole output, only a small part of it. Also, a large output from a command could tire them and could make them stop using our product We want
"our product" sounds bad, make it more like "stop using the application" or so?

2017-05-22 08:54 UTC, Adrianzatreanu commented on cEP-0010.md
> +Easier to remember an action based on the letters instead of numbers. (Do (n)othing).
an action based on a letter*

2017-05-22 08:55 UTC, Adrianzatreanu commented on cEP-0010.md
> +Users could apply more than one patch in a single input. The idea here is to offer more flexibility to our users. Instead of just 1 number, the user could enter more actions.
more actions, chained by commas etc etc

2017-05-22 08:56 UTC, Adrianzatreanu commented on cEP-0010.md
> +Google Form.
feedbacked gathered on the Google Form.

2017-05-22 08:58 UTC, Adrianzatreanu commented
i reviewed a bit of it but there's something i dont like at all. youre using a lot of "we will, we should, I will". This is not how a document, e.g. enhancement proposal should look like (nobody cares who wrote it).
Take a look at cep 02 for example, check how everything is written (third person):
This proposal aims to; A new class will be created; The bears will be handled by; etc, you dont see "We will create a new class". feel the difference?

2017-05-25 15:08 UTC, yukiisbored commented on cEP-0010.md
> +This cEP describes the design of coala's Command Line Interface (the action selection screen). It intended to refactor the design released as part of coala 0.8.
I think "It is intended ..." fits more.

2017-05-25 15:10 UTC, yukiisbored commented on cEP-0010.md
> +This cEP describes the design of coala's Command Line Interface (the action selection screen). It intended to refactor the design released as part of coala 0.8.
Also, Please limit to 80 chars.

2017-05-25 15:11 UTC, yukiisbored commented on cEP-0010.md
> +This cEP describes the design of coala's Command Line Interface (the action selection screen). It intended to refactor the design released as part of coala 0.8.
Please limit to 80 chars

2017-05-25 15:11 UTC, yukiisbored commented on cEP-0010.md
> +This cEP describes the design of coala's Command Line Interface (the action selection screen). It intended to refactor the design released as part of coala 0.8.
Please limit to 80 characters

2017-05-25 15:12 UTC, yukiisbored commented on cEP-0010.md
> +Adds functionality alongside with a better interaction with the user. The final goal is for coala CLI to be more friendly, easier to read and use. Adds more functionality depending on what user wants
Please limit to 80 characters

2017-05-25 15:19 UTC, yukiisbored commented on cEP-0010.md
> +Now users have the possibility to choose at every result an action. We want to add the possibility to choose an action for all results.
I find this to be quite confusing. I think "to choose an action for every results" would be a better choice.

2017-05-25 15:19 UTC, yukiisbored commented on cEP-0010.md
> +We should have an option that lets user choose whether they want another action after the current action is done. This way, users will have the flexibility in their hands.
I don't get what this means nor the use case for this.

2017-05-25 15:19 UTC, yukiisbored commented on cEP-0010.md
> +Masive changes should take place in 'result_actions' directory where are kept all the actions.
s/Masive/Massive/

2017-05-25 15:19 UTC, yukiisbored commented on cEP-0010.md
> +[    ] Enter the letters of the patches you want to apply('-' between any letter): a-i-n
s/apply('/apply ('/

2017-05-25 15:19 UTC, yukiisbored commented on cEP-0010.md
> +So, let's say that a user wants to add an ignore comment in all files.
s/let's/lets/

2017-05-25 15:19 UTC, yukiisbored commented on cEP-0010.md
> +The user should choose '(S)elect action for all results' and after, 'i' option.
I think "and Choose the 'i' option" would fit better. The comma placement is confusing.

2017-05-25 15:19 UTC, yukiisbored commented on cEP-0010.md
> +[    ] Enter the letters of the patches you want to apply('-' between any letter): a-i-n
Please add space between "apply" and "('-' between any letter):".

2017-05-25 15:19 UTC, yukiisbored commented on cEP-0010.md
> +[    ] Reprompt after running actions(Y/N)?
Same goes for here, add a space before the first parentheses

2017-05-25 15:19 UTC, yukiisbored commented on cEP-0010.md
> +### Set 'Do nothing' as the default action
Remove this, Duplication of https://github.com/coala/cEPs/pull/79/files#diff-dc65288ae3b8f48bf19e685ea3460ad6R59

2017-05-26 10:04 UTC, yukiisbored commented on cEP-0010.md
> +Google Form.
Did you mean, "feedback gathered from the Google Form"?

2017-05-26 12:22 UTC, Adrianzatreanu commented on cEP-0010.md
> +This cEP describes the design of coala's Command Line Interface (the action selection screen). It intended to refactor the design released as part of coala 0.8.
or that, still better than "it indended"

2017-05-26 12:23 UTC, Adrianzatreanu commented on cEP-0010.md
> +The section below describes why we should make these changes.
why these changes should be done*

2017-05-26 12:23 UTC, Adrianzatreanu commented on cEP-0010.md
> +make them stop using our application. We want to remove the redundant information,
no "we want"

2017-05-26 12:24 UTC, Adrianzatreanu commented on cEP-0010.md
> +Easier to remember an action based on a letter instead of numbers. (Do (n)othing).
Letters are easier to be remembered rather than numbers.

2017-05-26 12:24 UTC, Adrianzatreanu commented on cEP-0010.md
> +We want to add the possibility to choose an action for all results.
no "we want"

2017-05-26 12:24 UTC, Adrianzatreanu commented on cEP-0010.md
> +We should have an option that lets user choose whether they want another action after the current action is done. This way, users will have the flexibility in their hands.
no "we should"

2017-05-26 12:24 UTC, Adrianzatreanu commented on cEP-0010.md
> +The section below describe how we should make these changes.
describes*

2017-05-26 12:24 UTC, Adrianzatreanu commented on cEP-0010.md
> +Most of the text that should be changed is in the 'ConsoleInteraction.py' file. We should change that based on the feedback requested with
no "we should"

2017-05-26 12:25 UTC, Adrianzatreanu commented on cEP-0010.md
> +Google Form.
^

2017-05-26 12:25 UTC, Adrianzatreanu commented on cEP-0010.md
> +If one of the action requested isn't possible, an warning will be printed (after all possible actions are applied) with the letter that couldn't be satisfied.
a warning*

2017-05-26 15:28 UTC, yukiisbored requested changes
Please change the cEP number, It's conflicting with @Asnelchristian's cEP.

2017-05-28 20:48 UTC, Nosferatul commented
done @Adrianzatreanu @yukiisbored

2017-05-29 04:56 UTC, yukiisbored commented on cEP-0012.md
> +Most of the text that should be changed is in the 'ConsoleInteraction.py' file. Do changes based on the feedback requested with
I think it should be gathered not requested.

2017-05-29 04:57 UTC, yukiisbored commented on cEP-0012.md
> +Most of the people who use a CLI program do not read the whole output, only a
I think it should be "does not" since "Most of the people" is third-person

2017-05-29 04:59 UTC, yukiisbored commented on cEP-0012.md
> +---
Nothing to fill here or WIP until the next period?

2017-05-29 04:59 UTC, yukiisbored commented on cEP-0012.md
> +Most of the text that should be changed is in the 'ConsoleInteraction.py' file. Do changes based on the feedback requested with
Not to mention line 79  uses "gathered"

2017-05-29 09:04 UTC, Nosferatul commented on cEP-0012.md
> +---
I explained below or do you want something else?

2017-05-29 11:50 UTC, yukiisbored commented on cEP-0012.md
> +---
Well, line 69 said "The section below describes how we should make these changes". So yeah, explain it under this section.

2017-05-29 12:16 UTC, Nosferatul commented on cEP-0012.md
> +---
Hmm, do you want code? The idea is explained below for every change

2017-05-29 21:24 UTC, Adrianzatreanu commented on cEP-0012.md
> +This cEP describes the design of coala's Command Line Interface (the action selection screen). It intended to refactor the design released as part of coala 0.8.
it indends*!!!!!

2017-05-29 21:25 UTC, Adrianzatreanu commented on cEP-0012.md
> +Most of the people who use a CLI program does not read the whole output, only a
do not*

2017-05-29 21:30 UTC, Adrianzatreanu commented on cEP-0012.md
> +1. Make changes in the 'ConsoleInteraction.py' based on the feedback gathered with Google Form.
what is this 1?

2017-05-29 21:31 UTC, Adrianzatreanu commented on cEP-0012.md
> +If an user will press 'C':
it is "a user"
https://english.stackexchange.com/questions/105116/is-it-a-user-or-an-user

2017-05-29 21:32 UTC, Adrianzatreanu commented on cEP-0012.md
> +If one of the action requested isn't possible, a warning will be printed (after all possible actions are applied) with the letter that couldn't be satisfied.
actions*

2017-05-29 21:32 UTC, Adrianzatreanu commented on cEP-0012.md
> +3. Parse corecty the input
parse the input corRectly*

2017-05-29 21:32 UTC, Adrianzatreanu commented on cEP-0012.md
> +This should work if the user choose to (C)hain actions.
chooses

2017-05-29 21:32 UTC, Adrianzatreanu commented on cEP-0012.md
> +If the user choose 'Y', after all the actions are applied, the interface will be reprompted with the possible actions.
chooses

2017-05-30 07:49 UTC, yukiisbored commented on cEP-0012.md
> +---
Oh, didn't see that. Sorry :sweat_smile:

2017-05-30 11:15 UTC, yukiisbored submitted a review, later dismissed

2017-05-30 11:26 UTC, yukiisbored commented on cEP-0012.md
> +Most of the people who use a CLI program do not read the whole output, only a
nvm, it's correct.

2017-05-30 11:31 UTC, yukiisbored commented on cEP-0012.md
> +[    ] Do (N)othing
Please use the multi-line code blocks for the mock-ups. It looks weird in the "Rich text view"

2017-05-30 11:31 UTC, yukiisbored commented on cEP-0012.md
> +[    ] Do (N)othing
Please use the multi-line code blocks for the mock-ups. It looks weird in the "Rich text view"

2017-05-30 11:31 UTC, yukiisbored commented on cEP-0012.md
> +==== Apply an action for all results ====
Please use the multi-line code blocks for the mock-ups. It looks weird in the "Rich text view"

2017-05-30 11:31 UTC, yukiisbored commented on cEP-0012.md
> +[    ] Enter the letters of the patches you want to apply ('-' between any letter): a-i-n
Please use the multi-line code blocks for the mock-ups. It looks weird in the "Rich text view"

2017-05-30 11:31 UTC, yukiisbored commented on cEP-0012.md
> +[    ] Do (N)othing
Please use the multi-line code blocks for the mock-ups. It looks weird in the "Rich text view"

2017-05-30 11:31 UTC, yukiisbored commented on cEP-0012.md
> +[    ] Enter the letters of the patches you want to apply ('-' between any letter): a-i-n
Please use the multi-line code blocks for the mock-ups. It looks weird in the "Rich text view"

2017-05-30 13:49 UTC, yukiisbored commented
ack https://github.com/coala/cEPs/commit/ed65db9ff3441eb3eeeb39035eed10875aa27435

2017-05-30 13:49 UTC, yukiisbored commented
@rultor Please merge xoxo

2017-05-30 13:49 UTC, rultor commented
> @rultor Please merge xoxo

@yukiisbored OK, I'll try to merge now. You can check the progress of the merge [here](http://www.rultor.com/t/11826-304883988)

2017-05-30 13:50 UTC, merged

2017-05-30 13:51 UTC, rultor commented
> @rultor Please merge xoxo

@yukiisbored Done! FYI, the full log is [here](http://www.rultor.com/t/11826-304883988) (took me 2min)