WIP: cEP-0010.md: Convert bears to use aspects
coala/cEPs pull request #81
Opened 2017-05-12 19:45 UTC by Asnelchristian

2017-05-13 08:29 UTC, userzimmermann requested changes
@Asnelchristian Great start for **cEP-0010**! But keep your sentences a bit more clear and straight forward...

2017-05-13 08:29 UTC, userzimmermann commented on cEP-0010.md
> +This document describes how `aspects` will be implemented and bears' results
Better *"... how `aspects` will be defined for and connected with bears and how their results will be ..."*

2017-05-13 08:29 UTC, userzimmermann commented on cEP-0010.md
> +[cEP](https://github.com/coala/cEPs/blob/master/cEP-0005.md), one of the main
`[cEP-0005](...)`

2017-05-13 08:29 UTC, userzimmermann commented on cEP-0010.md
> +(with numerous settings) it offers; whereby the user has to be aware of bear
Better *"... due to the huge number of bears it offers, which are capable of analyzing several aspects of code and are sometimes highly configurable with numerous settings; whereby the user has to be aware of which bear does what..."*

2017-05-13 08:29 UTC, userzimmermann commented on cEP-0010.md
> +in [cEP](https://github.com/coala/cEPs/blob/master/cEP-0005.md). Our concern
`[cEP-0005](...)`

2017-05-13 08:29 UTC, userzimmermann commented on cEP-0010.md
> +in [cEP](https://github.com/coala/cEPs/blob/master/cEP-0005.md). Our concern
And *concern* --> *goal*

2017-05-13 08:29 UTC, userzimmermann commented on cEP-0010.md
> +here is to enumerate and implement all the `aspects` of code the bears offered
Better *enumerate* --> *list*

2017-05-13 08:29 UTC, userzimmermann commented on cEP-0010.md
> +be implemented in a tree-like form with root the [Root aspects](https://github.com/coala/coala/blob/master/coalib/bearlib/aspects/root.py).
Better *"... tree-like form starting with the `[Root aspect](...)`."*

2017-05-13 08:29 UTC, userzimmermann commented on cEP-0010.md
> +  |--- |--- | --- |--- Length
Put that whole block in triple backticks to keep the structure

2017-05-13 08:29 UTC, userzimmermann commented on cEP-0010.md
> +* [the aspectbase metaclass](https://github.com/coala/coala/blob/master/coalib/bearlib/aspects/base.py)
`aspectbase` is no metaclass

2017-05-13 08:29 UTC, userzimmermann commented on cEP-0010.md
> +* [the aspectclass](https://github.com/coala/coala/blob/master/coalib/bearlib/aspects/meta.py)
`aspectclass` is the actual metaclass :) So you could name the link `[the meta aspectclass](...)`

2017-05-13 08:29 UTC, userzimmermann commented on cEP-0010.md
> +* [the TasteMeta metaclass](https://github.com/coala/coala/blob/master/coalib/bearlib/aspects/taste.py)
No need for double *meta* ;) Just `[the TasteMeta class](...)` should be enough

2017-05-13 08:29 UTC, userzimmermann commented on cEP-0010.md
> +```
Also add some sample taste here

2017-05-13 08:29 UTC, userzimmermann commented on cEP-0010.md
> +## The aspests
What are *aspests* ;D

2017-05-13 08:29 UTC, userzimmermann commented on cEP-0010.md
> +The bears offered by coala are capable of several aspects of code, aspects will
Better *"... are usually capable of handling several aspects. aspects will..."*

2017-05-13 08:29 UTC, userzimmermann commented on cEP-0010.md
> +with the Root aspects at the root of the tree. Some classes, metaclasses
there is only one Root aspect ;)

2017-05-13 08:29 UTC, userzimmermann commented on cEP-0010.md
> +here is to enumerate and implement all the `aspects` of code the bears offered
And better something like  *"... all the aspects for covering all the code analysis features the coala bears are capable of..."*

2017-05-13 09:02 UTC, Asnelchristian commented on cEP-0010.md
> +with the Root aspects at the root of the tree. Some classes, metaclasses
sure... that is typo

2017-05-16 13:16 UTC, Udayan12167 commented on cEP-0010.md
> +  Root
I would want a description of the newly defined aspects in this cEP. What kind of changes are the bears under them expected to offer.

2017-05-16 13:18 UTC, Udayan12167 commented on cEP-0010.md
> +  Root
The explanation can be short and not too detailed but some info about each aspect would give anyone reading the cEP and idea of the project. Then this cEP could become the place for proposing any new aspect class.

2017-05-16 13:18 UTC, Udayan12167 commented on cEP-0010.md
> +  Root
Similarly add details about the tastes.

2017-05-22 09:10 UTC, userzimmermann requested changes
WOW! Great effort :) But there are some little issues left... But quick to fix :D

2017-05-22 09:10 UTC, userzimmermann commented on cEP-0010.md
> +correspponding `tastes` or `settings`.
Just shortly explain that tastes are customization settings for aspects here and then don't use the term *setting* anymore

2017-05-22 09:10 UTC, userzimmermann commented on cEP-0010.md
> +[cEP-0005](...), one of the main problems coala faces is its configuration due
I didn't mean to remove the https://github.com/coala/cEPs/blob/master/cEP-0005.md URL from the link here ;)

I just wanted `[cEP-0005]` instead of just `[cEP]`

2017-05-22 09:10 UTC, userzimmermann commented on cEP-0010.md
> +in [cEP-0005](...). Our goal here is to list all the aspects for covering all
Same as above. Reinsert the URL to `cEP-0005`

2017-05-22 09:10 UTC, userzimmermann commented on cEP-0010.md
> +`subaspects` and tastes or settings(which are the leaves of the tree written
Like stated in the `## Abstract` section above: No *settings* term anymore. Only `tastes`

2017-05-22 09:10 UTC, userzimmermann commented on cEP-0010.md
> +  |--- |--- |--- Ignore
aspects with tastes should not have further subaspects

2017-05-22 09:10 UTC, userzimmermann commented on cEP-0010.md
> +  |--- |--- |--- |--- line
Are those tastes or subaspects? If tastes, then they should be named a bit more verbose, like `ignore_links` and `ignore_line`

BTW: What is actually meant with ignoring line?

2017-05-22 09:10 UTC, userzimmermann commented on cEP-0010.md
> +  |--- Smell
You already have `Smell` above

2017-05-22 09:10 UTC, userzimmermann commented on cEP-0010.md
> +  |--- Undefined elements
`CamelCase` :)

2017-05-22 09:10 UTC, userzimmermann commented on cEP-0010.md
> +* `Root.Formatting`: This aspect checks on the format(the structure) of your
space before `(the structure)`

2017-05-22 09:10 UTC, userzimmermann commented on cEP-0010.md
> +* `Root.Formatting.EmptyLines.num_newlines_after_class_def`(Taste obj):
You don't need to mention `(Taste obj)`. You explained that they are the final `snake_case` leaves of the aspects tree. So it should be obvious that it's a taste

Applies to all below as well ;)

2017-05-22 09:10 UTC, userzimmermann commented on cEP-0010.md
> +Concerning bears' results annotation, so far, the `aspect` attr was added to
Better write `.aspect` to make it even quicker being recognized as an attribute

2017-05-22 09:10 UTC, userzimmermann commented on cEP-0010.md
> +Here is how bears' will be defined in as presented in [cEP-0005](...).
Also `cEP-0005` URL missing in link

2017-05-22 09:10 UTC, userzimmermann commented on cEP-0010.md
> +will be changed to `DETECT_ASPECTS` and `FIX_ASPECTS`.
Forgot that we threw the `DETECT_ASPECTS` and `FIX_ASPECTS` attributes away in favor of the metaclass based aspects definition? ;)

https://github.com/coala/cEPs/pull/72/commits/9aa3b43fa882e247a9fd15cea02c10614ca986cf#diff-7c040d00c1a93d80315fca153d104cdaR100

2017-05-22 09:12 UTC, Asnelchristian commented on cEP-0010.md
> +  |--- |--- |--- |--- line
`ignore_line` represents the list of lines that should be ignored

2017-05-22 09:13 UTC, Asnelchristian commented on cEP-0010.md
> +  |--- Smell
ooh my bad!

2017-05-22 09:13 UTC, userzimmermann reviewed
Just a remark for the future :)

2017-05-22 09:13 UTC, userzimmermann commented on cEP-0010.md
> +`Root.Metadata.CommitMessage.Body.Length.max_body_length`(Taste obj).
IMO we should just link to aspect docs here later instead of describing every aspect and taste here again

2017-05-22 09:28 UTC, Asnelchristian commented on cEP-0010.md
> +`Root.Metadata.CommitMessage.Body.Length.max_body_length`(Taste obj).
awesome idea

2017-05-22 09:28 UTC, Asnelchristian commented on cEP-0010.md
> +will be changed to `DETECT_ASPECTS` and `FIX_ASPECTS`.
my bad

2017-05-23 21:25 UTC, userzimmermann requested changes
Little syntax errors in code example

2017-05-23 21:25 UTC, userzimmermann commented on cEP-0010.md
> +        'fix': [Root.Redundancy.UnusedImport,
Forgot to close `'fix':` list with `]` and `aspects=` dict with `}`

2017-05-23 21:36 UTC, userzimmermann requested changes
Some extra improvements for code examples

2017-05-23 21:36 UTC, userzimmermann commented on cEP-0010.md
> +            # Bears can access settings right from the aspect instance
*settings* --> *tastes*

2017-05-23 21:36 UTC, userzimmermann commented on cEP-0010.md
> +#This will serve as documentation for the aspect
Indent the comment and put space after `#`

2017-05-23 21:36 UTC, userzimmermann commented on cEP-0010.md
> +#aspects are not compelled to have tastes
And also indent those comments and put a space after each `#`

2017-05-23 21:36 UTC, userzimmermann commented on cEP-0010.md
> +#This will serve as documentation for the aspect
Better put a newline above

2017-05-23 21:36 UTC, userzimmermann commented on cEP-0010.md
> +#Here we define the different tastes for this aspect
And also better put a newline above here

2017-05-23 21:39 UTC, userzimmermann reviewed
@Asnelchristian And one last thing :) No need to make changes now... Only need to discuss later!

2017-05-23 21:39 UTC, userzimmermann commented on cEP-0010.md
> +        aspect = aspects.get(Root.Redundancy.Clone, False)
We haven't decided on a data type for the `aspects` argument yet... You are just assuming a dict here that maps aspectclasses to aspect instances... Don't know if that's the best idea! But let's just leave it for now and refine later :)

2017-05-23 22:04 UTC, userzimmermann approved these changes

2017-05-23 22:06 UTC, userzimmermann commented
ack https://github.com/coala/cEPs/pull/81/commits/3c5ec9785b03be715624e22873951a48b2aa035a

2017-05-23 22:06 UTC, userzimmermann commented
@rultor merge

2017-05-23 22:09 UTC, rultor commented
> @rultor merge

@userzimmermann OK, I'll try to merge now. You can check the progress of the merge [here](http://www.rultor.com/t/11744-303546279)

2017-05-23 22:11 UTC, merged

2017-05-23 22:12 UTC, rultor commented
> @rultor merge

@userzimmermann Done! FYI, the full log is [here](http://www.rultor.com/t/11744-303546279) (took me 2min)